Error processing line 1 of /home/tkadelka/.local/lib/python3.7/site-packages/autorunrecord-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.7/site.py", line 174, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
[WARNING] realpath of PWD=/data/project/rehab_eNKI/eNKI_data/code is /data/project/rehab_eNKI/eNKI_data/code whenever os.getcwd()=/data/project/rehab_eNKI/eNKI_data. From now on will be returning os.getcwd(). Directory symlinks in the paths will be resolved 
[INFO] Downloading 'https://trends-coins-ni.s3.amazonaws.com/nidropbox/8100_anonymized/20180424_045759_EiQTn.zip?response-content-disposition=attachment%3Bfilename%3Dscan_data476.zip&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2V4PE5I4KOKW2K76%2F20200211%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200211T005355Z&X-Amz-SignedHeaders=host&X-Amz-Expires=604800&X-Amz-Signature=76464f30d2c9231822f5622a81c465829214b5619815dd6fbec973e35ed0e86e' into '/data/project/rehab_eNKI/eNKI_data/' 
